package com.ycszh.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * BaseServiceImplService service = new BaseServiceImplService();
 * BaseService portType = service.getBaseServiceImplPort();
 * portType.callService(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "BaseServiceImplService", targetNamespace = "http://impl.service.base.psbp.soa.cn.iaspec.com/", wsdlLocation = "http://100.100.195.28:8080/service-client/ws/service?wsdl")
public class BaseServiceImplService extends Service {

	private final static URL BASESERVICEIMPLSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.ycszh.webservice.BaseServiceImplService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.ycszh.webservice.BaseServiceImplService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://100.100.195.28:8080/service-client/ws/service?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://100.100.195.28:8080/service-client/ws/service?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		BASESERVICEIMPLSERVICE_WSDL_LOCATION = url;
	}

	public BaseServiceImplService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public BaseServiceImplService() {
		super(BASESERVICEIMPLSERVICE_WSDL_LOCATION, new QName(
				"http://impl.service.base.psbp.soa.cn.iaspec.com/",
				"BaseServiceImplService"));
	}

	/**
	 * 
	 * @return returns BaseService
	 */
	@WebEndpoint(name = "BaseServiceImplPort")
	public BaseService getBaseServiceImplPort() {
		return super.getPort(new QName(
				"http://impl.service.base.psbp.soa.cn.iaspec.com/",
				"BaseServiceImplPort"), BaseService.class);
	}

}
