package com.ycszh.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "BaseService", targetNamespace = "http://base.inf.service.common.iaspec.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface BaseService {

	/**
	 * 
	 * @param arg0
	 * @return returns java.lang.String
	 * @throws Exception_Exception
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String callService(
			@WebParam(name = "arg0", partName = "arg0") String arg0)
			throws Exception_Exception;

}
